language: java
install: true
script:
    - ./gradlew -p setup-android-sdk
    - ./gradlew -p setup-android-sdk publishToMavenLocal
    - ./gradlew -p example-android-project assemble
    - ./gradlew -p example-android-project cleanLocalProperties # Ensure this task works
deploy: