env:
  - GRADLE_OPTS="-Dorg.gradle.console=plain -Dgradle.publish.key='$GRADLE_PUBLISH_KEY' -Dgradle.publish.secret='$GRADLE_PUBLISH_SECRET'"
os:
  - linux
dist: xenial
language: android
jdk:
  - openjdk8
  - openjdk10
install: true
script:
  - ./gradlew -p setup-android-sdk
  - ./gradlew -p setup-android-sdk publishToMavenLocal # Publish locally to consume in example-android-project
  - ./validate_plugin
deploy:
  - provider: script
    script: ./gradlew -p setup-android-sdk publishPlugins
    on:
      branch: master
      tags: true
      jdk: openjdk8
