language: java
install: true
script:
    - ./gradlew -p setup-android-sdk
    - ./gradlew -p setup-android-sdk publishToMavenLocal # Publish locally to consume in the example
    - ./gradlew -p example-android-project assemble
    - ./gradlew -p example-android-project cleanLocalProperties # Ensure this task exists
deploy:
    - provider: script
      script: ./gradlew -p setup-android-sdk publishPlugins
      on:
        branch: master
